### ISSUE TITLE
Can't find the compass-retinator lib

### ISSUE THREAD

**Issue by wvddrss** [restorando/compass-retinator#1]
i've installed the gem

gem install compass-retinator

i've added the rule in config.rb

require "compass-retinator"

and when i compile i get this error:

LoadError on line ["45"] of  <userfolder>/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- compass_retinator
   <userfolder>/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'

I reinstalled compass and retinator, but same issue

my ruby verison:
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin11.4.2]

**Comment by jbarreneche** [comment]
Hi,
Are you sure the require in your `config.rb` for `compass-retinator` has a dash `-` instead of an underscore `_`?

Your backtrace shows `compass_retinator` instead of `compass-retinator`
