### ISSUE TITLE
Compatibility with Compass 1

### ISSUE THREAD

**Issue by jesseschutt** [restorando/compass-retinator#5]
Hello!

I was wondering if this was compatible with Compass version 1.0.0.alpha.19 or greater? 

Thanks

**Comment by jesseschutt** [comment]
The reason I'm asking is that on my next project I want to use Susy 2, which requires Sass 3.3.5. The only version of Compass that will work on that version of sass is 1.0.0.alpha19. Hence the reason for asking about Compass-Retinator's compatibility with that pre-release of Compass. :-)

Thanks!

**Comment by baires** [comment]
Good question @jschutt I will look into that over the weekend and will be back to you

**Comment by broseff-zz** [comment]
Doesn't look like this extension is compatible with compass 1.0.1, I'm getting and "extension not found" error when compiling.  :(

**Comment by 1stevengrant** [comment]
You can actually get it compile fine with Compass 1.0.1 but not using the gem. If you add this https://gist.github.com/stevieg83/cb79fcfd93ae8a39a4f5 as a mixin to your project, it'll compile just the same.

**Comment by rootical** [comment]
I used retinator in my rails application. 

But in different project based on node.js and grunt-contrib-compass  (which is not using the compass-retinator) i can't compile anymore, Unable to load extension: compass-retinator.

What shall I do?

**Comment by baires** [comment]
@rootical Try using tit as an standalone mixin. Just do an `@import` of [_retinator.sass](https://github.com/restorando/compass-retinator/blob/master/stylesheets/partials/_retinator.sass) on your main application.sass

**Comment by rootical** [comment]
But i don't use it at all in that project, that's what I'm saying.

**Comment by 1stevengrant** [comment]
it must be referenced somewhere if it's trying to compile.

**Comment by baires** [comment]
Try cleaning up the gem

`gem cleanup compass-retinator`

or delete compass_retinator for dirty solution

`gem uninstall compass-retinator`

**Comment by rootical** [comment]
Using an older version of compass helped. I've just deleted the last.
